INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('123', 'contact@manning.com', 0, 'Manning', 'Java in Action');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('124', 'contact@apress.com', 1, 'Apress', 'Spring for All');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('125', 'contact@manning.com', 0, 'Manning', 'Java in Practice');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('126', 'sdfe@apress.com', 1, 'Apress', 'Spring Recipes');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('127', 'ccfd@manning.com', 2, 'Manning', 'Oracle in Action');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('128', 'contact@apress.com', 3, 'Apress', 'Python Dummies');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('134', 'contact@tmh.com', 0, 'TMH', 'Core Java ');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('129', 'contact@pearson.com', 1, 'Pearson', 'Spring Cookbook');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('130', 'contact@willy.com', 2, 'Willy', 'Oracle PLSQL');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('131', 'contact@spectrum.com', 3, 'Spectrum', 'Python Cookbook');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('132', 'contact@manning.com', 2, 'Manning', 'Spring in Action');
INSERT INTO BOOK(ISBN, AUTHOR_EMAIL, CATEGORY, PUBLISHER, TITLE) VALUES('133', 'contact@willy.com', 1, 'Willy', 'Spring Fundamentals');